branches:
  only:
  - master
os: windows
language: sh
python: "3.7"
before_install:
  - choco install python3
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
install:
  - pip -V
  - pip install -r requirements.txt
script:
  - pyinstaller -w --onefile src/main.py
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "dist/main.exe"
  skip_cleanup: true
  on:
    tags: true
